config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  delete '/products', to: 'products#destroy_all'
  patch '/products', to: 'products#check_all'

  resources :allergens
  delete '/allergens', to: 'allergens#destroy_all'

  resources :menus, only: [:index, :create]
  
  get '/reactions', to: 'reactions#index'

  resources :profiles, only: [:show, :edit]
  
  #CRUD is not applicable so resource is not an appropriate choice,
  #instead manually build routes 
  #/search is the route, it points to (=>) searches#search (controller_name#action  where action is a function) 
  get '/search' => 'searches#search', as: 'search_search'
  #root 'allergens#index'
  #root 'products#new'
  root 'products#index'

=begin
  #When we use resources routes, we are mapping the browser 
  #requests (HTTP verbs and URLs) to the controller actions 
  #of our app
  # 'rails routes' will produce:
  # all routes which are mapped to: controller actions (Order of declaration matters)
  # get '/products', to: 'products#index', as: 'products_path'
  # get '/products/:id', to: 'products#show', as: 'post_path(object)'
  # get '/products/:id/edit', to: 'products#edit', as: 'edit_product_path(object)'
  # get '/products/new', to: 'products#new', as: 'new_product_path'
  # post '/products', to: 'products#create'
  # patch '/products/:id', to: 'products#update'
  # delete '/products/:id', to: 'products#destroy'
  # resource routing maps routes to controller actions replacing code above
  # with a single line of code:   "resources :products"
=end

end

app/models/allergen.rb
class Allergen < ApplicationRecord
  #The model should be able to answer the question "Can user x do y to this object?"
  #When you write regular methods in the model those methods are all instance methods.  
  #In other words def some_method will be a method available on each retrieved record

  # dependent: :destroy, rails will destroy all reactions associated with Allergen when its deleted
  has_many  :reactions, dependent: :destroy
  # A has_many :through association is often used to set up a many-to-many connection 
  # with another model (Reaction). This association indicates that the declaring model (Allergen) can be 
  # matched with zero or more instances of another model (Product) by proceeding through a third model (Reaction).
  has_many  :products, through: :reactions
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'

  validates :category, presence: true
  #to validate more than one column (or more), you can add that to the scope
  validates_uniqueness_of :category, presence: true, :case_sensitive => false, :scope => [:user_id], length: {minimum: 3}
  validates :substances, presence: true, length: {minimum: 3}
  #Match any characters as few as possible until a ";" is found, without counting the ";".
  validates :substances, format: { with: /.+?(?=;)/, :message => "must end with or be seperated by a ';'" }
  
  #remove newline(\n) and return(\r) from substances attribute
  def substances=(value)
    write_attribute(:substances, value.gsub("\n","").gsub("\r",""))
  end

  def get_substances
    return self.substances.split(';')
  end

  # array of substances match the ingredient
  def matching_substances_to(ingredient)
    matching_substances = []
    # does ingredient match any substance in this allergen category 
    matching_substances = self.get_substances.select {|substance| 
        (ingredient.upcase.include?(substance.upcase) || substance.upcase.include?(ingredient.upcase))
      } 
    return matching_substances
  end

  # After allergen has been created or updated (and saved) check all products for
  # this allergen
  after_save do |allergen|
    if Product.any?
      Product.find_each {|product| product.check_for_allergens}
    end
  end 

end

app/controllers/allergens_controller.rb
class AllergensController < ApplicationController
  # Use before_action to set up an instance variable for an action, 
  # in this case, call set_allergen before calling edit or destroy
  before_action :set_allergen, only: [:edit, :destroy, :update, :show]
  before_action :authenticate_user!, only: [:index]

# run 'rails routes' then add '_path' to the Prefix to get the url

#       Prefix Verb   URI Pattern                   Controller#Action
#---------------------------------------------------------------------
#    allergens GET    /allergens(.:format)          allergens#index
#              POST   /allergens(.:format)          allergens#create
# new_allergen GET    /allergens/new(.:format)      allergens#new
#edit_allergen GET    /allergens/:id/edit(.:format) allergens#edit
#     allergen GET    /allergens/:id(.:format)      allergens#show
#              PATCH  /allergens/:id(.:format)      allergens#update
#              PUT    /allergens/:id(.:format)      allergens#update
#              DELETE /allergens/:id(.:format)      allergens#destroy
#         root GET    /                             allergens#index

# The purpose of the controller is to manage the incoming request and session

# GET '/'
  def index
    # Allergens.all accesses model layer and stores result in an instance variable
    # which is passed to the view
    @allergens = Allergen.where("user_id = ?", current_user)
    # render 'allergens/index' happens by default at end of method
  end

  # GET '/allergens/new'
  def new
    # set up a new instance variable which is an active record object
    # and pass it to the 'new' template in "new.html.erb" 
    @allergen = Allergen.new
    # render 'allergens/new' happens by default at end of method
  end

  # GET '/allergens/:id/edit'
  def edit # url will be something like /allergens/"Formaldehyde"/edit, edit form will be rendered
    # @allergen = Allergen.find_by category: params[:id]... this is now done by set_allergen
    # render 'allergens/edit by default
  end

  # POST '/allergens'
  # the general pattern used in the action create that handles
  # submission of model-backed forms 
  def create 
    # the form displayed in "new.html.erb" is submitted to action='/allergens' 
    # using verb method="post" which is routed to allergens#create.
    # @allergen, is populated with values (params) submitted from the form
    @allergen = Allergen.new(allergen_params)
    @allergen.creator = current_user

    if @allergen.save #returns "false" if it can't save
      flash[:success] = "Allergen was successfully created. Products re-checked for new Allergen."
      # redirect must be a url, can't render a view template
      # (add '_path' to the prefix to get the url)
      redirect_to allergen_path(@allergen) # index
    else
      # validation error occured. We must render to have access to 
      # "allergens.error.full_messages" array to display generated errors 
      render 'new'
    end
  end

  # PATCH '/allergens/:id'
  #the general pattern used in the action create that handles
  #submission of model-backed forms 
  def update # this is where the form displayed in 'edit' is submitted using verb "patch"
    # we have @allergen because set_allergen was invoked by before_action
    if @allergen.update(allergen_params)
      flash[:success] = "Allergen was successfully updated. Products re-checked to reflect update."
      redirect_to allergen_path(@allergen)
    else
      render 'edit'
    end
  end

  # GET '/allergens/:id'
  def show
    #already have @allergen at this point because 'set_allergen' was invoked by before_action
    #render 'allergens/show' (show.html.erb) automatically called before exiting this method
  end

  # DELETE '/allergens/:id'
  def destroy
    # already have @allergen at this point because 'set_allergen' was invoked
    @allergen.destroy
    flash[:success] = "Allergen was successfully deleted"
    redirect_to allergens_path # show.html.erb
  end

  def destroy_all
    # already have @allergen at this point because 'set_allergen' was invoked
    Allergen.destroy_all
    flash[:success] = "Allergens successfully deleted"
    redirect_to allergens_path # allergens/index
  end

  private

  def set_allergen
    # ask ActiveRecord to find the Allergen object in the db using 
    # either :category or :id from params and current user. Must check if string params[:id]
    # contains an integer ie: "12" or category ie: "Disperse Orange"
    !!params[:id].match(/^(\d)+$/) ?
      (@allergen = Allergen.find_by id: params[:id], user_id: current_user.id) :
      (@allergen = Allergen.find_by category: params[:id], user_id: current_user.id)
  end

  def allergen_params
    # use strong parameters to expose the fields we're interested in
    # require top level key be allergen and allow changes to category, substances
    params.require(:allergen).permit(:category, :substances)
    # To permit all attributes params.require(:post).permit!
  end

end

app/views/allergens/_form.html.erb
<div class='row'>
  <div class='form-horizontal col-lg-6 col-lg-offset-3'>
    <%= form_for(@allergen, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="col-lg-12">
          <%= f.label :category, :class => "label-style text-color-not-ok"%>
        </div>
        <div class="col-lg-12">
          <%= f.text_field :category, id:"form-input", class: "form-control", placeholder: "Name of Allergen", autofocus: true %>
        </div>
      </div>
      <br>
      <div class="form-group">
        <div class="col-lg-12">
          <%= f.label :substances, :class => "label-style text-color-not-ok"%>
        </div>
        <div class="col-lg-12">
          <%= f.text_area :substances, id: "form-textarea", class: "form-control", placeholder: "substance 1; substance2; ... " %>
        </div>
      </div>  
      <div class="form-group col-lg-12 center">
        <button type="submit" class="btn btn-my-primary btn-xlarge">Save</button>
      </div>
    <% end %>
    <br>
    <div class="center">
      <%= link_to "Cancel request and return to products listing", products_path %>
    </div>
  </div>
</div>

app/views/allergens/edit.html.erb
<h1 class="center-heading label-color">Edit Allergen</h1>

<%= render 'form'%>

<script>
  formStyle()
</script>

app/views/allergens/index.html.erb
<body>
  <h1 class="center-heading label-color"><strong>Allergens</strong></h1>
  <%= render partial: "shared/allergen", collection: @allergens, :locals => {search_item: ""} %>
  <br>
  <div class="center">
    <%= link_to "Add New Allergen", new_allergen_path, class: "btn btn-xlarge btn-my-primary" %>
    <%= link_to "Select From Allergens Menu", menus_path, class: "btn btn-xlarge btn-my-primary" %>
  </div>
  <br>
</body>

app/views/allergens/new.html.erb
<h1 class="center-heading text-color-not-ok">Add a New Allergen</h1>

<%= render 'shared/errors', obj: @allergen %>
<!-- would provide the @allergen object to the partial, available under the local variable obj -->
<%= render 'form'%>

<script>
  formStyle()
</script>

app/views/allergens/show.html.erb
<%= render partial: 'shared/allergen', collection: Array(@allergen), :locals => {search_item: ""}  %>
<script>
  largePanel()
</script>