config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  delete '/products', to: 'products#destroy_all'
  patch '/products', to: 'products#check_all'

  resources :allergens
  delete '/allergens', to: 'allergens#destroy_all'

  resources :menus, only: [:index, :create]
  
  get '/reactions', to: 'reactions#index'

  resources :profiles, only: [:show, :edit]
  
  #CRUD is not applicable so resource is not an appropriate choice,
  #instead manually build routes 
  #/search is the route, it points to (=>) searches#search (controller_name#action  where action is a function) 
  get '/search' => 'searches#search', as: 'search_search'
  #root 'allergens#index'
  #root 'products#new'
  root 'products#index'

=begin
  #When we use resources routes, we are mapping the browser 
  #requests (HTTP verbs and URLs) to the controller actions 
  #of our app
  # 'rails routes' will produce:
  # all routes which are mapped to: controller actions (Order of declaration matters)
  # get '/products', to: 'products#index', as: 'products_path'
  # get '/products/:id', to: 'products#show', as: 'post_path(object)'
  # get '/products/:id/edit', to: 'products#edit', as: 'edit_product_path(object)'
  # get '/products/new', to: 'products#new', as: 'new_product_path'
  # post '/products', to: 'products#create'
  # patch '/products/:id', to: 'products#update'
  # delete '/products/:id', to: 'products#destroy'
  # resource routing maps routes to controller actions replacing code above
  # with a single line of code:   "resources :products"
=end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile

  def show
    #render 'profile/show' by default
  end

  # GET '/profile/:id/edit'
  def edit # url will be something like /profile/3/edit, goto devise registration form
    redirect_to edit_user_registration_path
  end

  private

    def set_profile
      #devise gives us current_user
      @current_user = current_user
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :address, :phone, :about, :email, :password)
    end
end

app/views/profiles/show.html.erb
<div class="row">
    <div class="col-lg-5 col-sm-offset-5">
      <fieldset class="custom-well">  
        <h3 class='profile-label'>First name</h3>
        <div class='profile-box'><%= @current_user.first_name %></div>

        <h3 class='profile-label'>Last name</h3>
        <div class='profile-box'><%= @current_user.last_name %></div>

        <h3 class='profile-label'>Address</h3>
        <div class='profile-box'><%= @current_user.address %></div>

        <h3 class='profile-label'>Phone</h3>
        <div class='profile-box'><%= @current_user.phone %></div>
       
        <h3 class='profile-label'>About</h3>
        <div class='profile-text-box'><%= @current_user.about %></div>

        <br>
        <button type="button" class="actions btn btn-my-primary btn-lg"><%= link_to "Edit Profile", edit_profile_path(@current_user.id)  %></button>
      </fieldset>
    </div>
</div>