config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  delete '/products', to: 'products#destroy_all'
  patch '/products', to: 'products#check_all'

  resources :allergens
  delete '/allergens', to: 'allergens#destroy_all'

  resources :menus, only: [:index, :create]
  
  get '/reactions', to: 'reactions#index'

  resources :profiles, only: [:show, :edit]
  
  #CRUD is not applicable so resource is not an appropriate choice,
  #instead manually build routes 
  #/search is the route, it points to (=>) searches#search (controller_name#action  where action is a function) 
  get '/search' => 'searches#search', as: 'search_search'
  #root 'allergens#index'
  #root 'products#new'
  root 'products#index'

=begin
  #When we use resources routes, we are mapping the browser 
  #requests (HTTP verbs and URLs) to the controller actions 
  #of our app
  # 'rails routes' will produce:
  # all routes which are mapped to: controller actions (Order of declaration matters)
  # get '/products', to: 'products#index', as: 'products_path'
  # get '/products/:id', to: 'products#show', as: 'post_path(object)'
  # get '/products/:id/edit', to: 'products#edit', as: 'edit_product_path(object)'
  # get '/products/new', to: 'products#new', as: 'new_product_path'
  # post '/products', to: 'products#create'
  # patch '/products/:id', to: 'products#update'
  # delete '/products/:id', to: 'products#destroy'
  # resource routing maps routes to controller actions replacing code above
  # with a single line of code:   "resources :products"
=end

end

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header navbar-left">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="sr-only">Toggle navigation</span>
      </button>
      <%= link_to "Product-OK", root_path, class: "navbar-brand", id:"logo" %>
    </div>
    <% if user_signed_in? %>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav nav-tabs nav-justified">
          <!-- Dropdown for Allergens -->
          <li role="presentation" class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              <strong>Allergens <span class="caret"></span></strong>
            </a>
            <ul class="dropdown-menu">
              <li><a href="/allergens">List My Allergens</a></li>
              <li><a href="/allergens/new">Add an Allergen to my List</a></li>
              <li><a href="/menus">Select Allergens from Menu</a></li>
              <li role="separator" class="divider"></li>
              <li><a data-confirm="Are you sure you want to delete all Allergens?" rel="nofollow" data-method="delete" href="/allergens">Delete <strong>ALL</strong> My Allergens</a></li>
            </ul>
          </li>
          <!-- Dropdown for Products ****** will never execute *****-->
          <% if (1<0) %>
            <li role="presentation" class="dropdown">
              <a class="dropdown-toggle my-nav-tab" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                <strong> Products <span class="caret"></span></strong>
              </a>
              <ul class="dropdown-menu">
                <li><a href="/products">List My Products</a></li>
                <li><a href="/products/new">Add Product To My List</a></li>
                <li><a href="/reactions">List Products Containing Allergens</a></li>
                <li><a rel="nofollow" data-method="patch" href="/products">Re-check All My Products For Allergens</a></li>
                <li role="separator" class="divider"></li>
                <li><a data-confirm="Are you sure you want to delete all Products?" rel="nofollow" data-method="delete" href="/products">Delete <strong>ALL</strong> My Products</a></li>
              </ul>
            </li>
          <% end %>
          <!--  Search --> 
          <li role="presentation">
            <div  class = "btn-group">
              <%= form_tag(search_search_path, :method => "get",class: 'navbar-form') do %>  
                <div class="input-group">  
                  <%= text_field_tag :search, params[:search], placeholder: "Search...", class: "form-control", size: 60 %>  
                  <div class="input-group-btn">  
                    <%= button_tag "Search", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil %>
                  </div>  
                </div> 
              <% end %>
            </div>
          </li>
          <!-- Profile and Log Out buttons -->
          <li role="presentation">
            <div class="text-right">
              <%= link_to profile_path(current_user.id), class: "btn-profile" do %>
                  <span class="glyphicon glyphicon-user"></span>
              <% end %>
              <%= link_to destroy_user_session_path, class: "btn-group btn btn-danger btn-lg btn-logout", method: :delete do %>Log out 
                <span class="glyphicon glyphicon-log-out"></span>
              <% end %>
            </div>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    <% end %>
  </div><!-- /.container-fluid -->
</nav>
<% if user_signed_in? %>
  <div id="add-product">
    <a href="/products/new">
      <span class="glyphicon glyphicon-plus"></span> Product 
    </a>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!-- Code in this file is available to the entire site -->
<!DOCTYPE html>
<html>
  <head>
    <title>Product-Ok</title>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"> 
      <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js', 'data-turbolinks-track' => true %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %> 
      <%= javascript_include_tag 'application','data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
    </script>
  </head>

  <body>
    <!-- navbar -->
    <%= render 'layouts/navigation' %> 
    <!-- validation error messages -->
    <%= render 'layouts/messages' %>
    <!-- views -->
    <div class='container-fluid'>
      <%= yield %>
    </div>
    <!-- Load in .js files dynamically when you need them: 
    <script>
      <%= javascript_include_tag 'application','data-turbolinks-track' => true %>
      <%= yield :javascript_includes %>
    </script>
    -->
  </body>
</html>